[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = [
  'npx prisma generate --schema=./prisma/schema.prisma',
  'npx prisma migrate deploy --schema=./prisma/schema.prisma',
  'node prisma/seed-production.js'
]

[start]
cmd = 'npm start'